/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPlaybookRouteImport } from './routes/_app/playbook'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppOffersRouteImport } from './routes/_app/offers'
import { Route as AppNotesRouteImport } from './routes/_app/notes'
import { Route as AppMyWeekRouteImport } from './routes/_app/my-week'
import { Route as AppInboxRouteImport } from './routes/_app/inbox'
import { Route as AppFollowUpsRouteImport } from './routes/_app/follow-ups'
import { Route as AppFlyersRouteImport } from './routes/_app/flyers'
import { Route as AppDixonRouteImport } from './routes/_app/dixon'
import { Route as AppCallRouteImport } from './routes/_app/call'
import { Route as AppCalendarRouteImport } from './routes/_app/calendar'
import { Route as ApiPublicGoogleCallbackRouteImport } from './routes/api/public/google.callback'
import { Route as ApiPublicDixonSplatRouteImport } from './routes/api/public/dixon.$'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybookRoute = AppPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppOffersRoute = AppOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppNotesRoute = AppNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AppRoute,
} as any)
const AppMyWeekRoute = AppMyWeekRouteImport.update({
  id: '/my-week',
  path: '/my-week',
  getParentRoute: () => AppRoute,
} as any)
const AppInboxRoute = AppInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppFlyersRoute = AppFlyersRouteImport.update({
  id: '/flyers',
  path: '/flyers',
  getParentRoute: () => AppRoute,
} as any)
const AppDixonRoute = AppDixonRouteImport.update({
  id: '/dixon',
  path: '/dixon',
  getParentRoute: () => AppRoute,
} as any)
const AppCallRoute = AppCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => AppRoute,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicGoogleCallbackRoute = ApiPublicGoogleCallbackRouteImport.update({
  id: '/api/public/google/callback',
  path: '/api/public/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDixonSplatRoute = ApiPublicDixonSplatRouteImport.update({
  id: '/api/public/dixon/$',
  path: '/api/public/dixon/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/calendar': typeof AppCalendarRoute
  '/call': typeof AppCallRoute
  '/dixon': typeof AppDixonRoute
  '/flyers': typeof AppFlyersRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/inbox': typeof AppInboxRoute
  '/my-week': typeof AppMyWeekRoute
  '/notes': typeof AppNotesRoute
  '/offers': typeof AppOffersRoute
  '/pipeline': typeof AppPipelineRoute
  '/playbook': typeof AppPlaybookRoute
  '/api/public/dixon/$': typeof ApiPublicDixonSplatRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/calendar': typeof AppCalendarRoute
  '/call': typeof AppCallRoute
  '/dixon': typeof AppDixonRoute
  '/flyers': typeof AppFlyersRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/inbox': typeof AppInboxRoute
  '/my-week': typeof AppMyWeekRoute
  '/notes': typeof AppNotesRoute
  '/offers': typeof AppOffersRoute
  '/pipeline': typeof AppPipelineRoute
  '/playbook': typeof AppPlaybookRoute
  '/': typeof AppIndexRoute
  '/api/public/dixon/$': typeof ApiPublicDixonSplatRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/calendar': typeof AppCalendarRoute
  '/_app/call': typeof AppCallRoute
  '/_app/dixon': typeof AppDixonRoute
  '/_app/flyers': typeof AppFlyersRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/inbox': typeof AppInboxRoute
  '/_app/my-week': typeof AppMyWeekRoute
  '/_app/notes': typeof AppNotesRoute
  '/_app/offers': typeof AppOffersRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/playbook': typeof AppPlaybookRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/dixon/$': typeof ApiPublicDixonSplatRoute
  '/api/public/google/callback': typeof ApiPublicGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calendar'
    | '/call'
    | '/dixon'
    | '/flyers'
    | '/follow-ups'
    | '/inbox'
    | '/my-week'
    | '/notes'
    | '/offers'
    | '/pipeline'
    | '/playbook'
    | '/api/public/dixon/$'
    | '/api/public/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/calendar'
    | '/call'
    | '/dixon'
    | '/flyers'
    | '/follow-ups'
    | '/inbox'
    | '/my-week'
    | '/notes'
    | '/offers'
    | '/pipeline'
    | '/playbook'
    | '/'
    | '/api/public/dixon/$'
    | '/api/public/google/callback'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/calendar'
    | '/_app/call'
    | '/_app/dixon'
    | '/_app/flyers'
    | '/_app/follow-ups'
    | '/_app/inbox'
    | '/_app/my-week'
    | '/_app/notes'
    | '/_app/offers'
    | '/_app/pipeline'
    | '/_app/playbook'
    | '/_app/'
    | '/api/public/dixon/$'
    | '/api/public/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicDixonSplatRoute: typeof ApiPublicDixonSplatRoute
  ApiPublicGoogleCallbackRoute: typeof ApiPublicGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbook': {
      id: '/_app/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AppPlaybookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/offers': {
      id: '/_app/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AppOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notes': {
      id: '/_app/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AppNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-week': {
      id: '/_app/my-week'
      path: '/my-week'
      fullPath: '/my-week'
      preLoaderRoute: typeof AppMyWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inbox': {
      id: '/_app/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AppInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/flyers': {
      id: '/_app/flyers'
      path: '/flyers'
      fullPath: '/flyers'
      preLoaderRoute: typeof AppFlyersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dixon': {
      id: '/_app/dixon'
      path: '/dixon'
      fullPath: '/dixon'
      preLoaderRoute: typeof AppDixonRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call': {
      id: '/_app/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof AppCallRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calendar': {
      id: '/_app/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/google/callback': {
      id: '/api/public/google/callback'
      path: '/api/public/google/callback'
      fullPath: '/api/public/google/callback'
      preLoaderRoute: typeof ApiPublicGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dixon/$': {
      id: '/api/public/dixon/$'
      path: '/api/public/dixon/$'
      fullPath: '/api/public/dixon/$'
      preLoaderRoute: typeof ApiPublicDixonSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCalendarRoute: typeof AppCalendarRoute
  AppCallRoute: typeof AppCallRoute
  AppDixonRoute: typeof AppDixonRoute
  AppFlyersRoute: typeof AppFlyersRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppInboxRoute: typeof AppInboxRoute
  AppMyWeekRoute: typeof AppMyWeekRoute
  AppNotesRoute: typeof AppNotesRoute
  AppOffersRoute: typeof AppOffersRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPlaybookRoute: typeof AppPlaybookRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCalendarRoute: AppCalendarRoute,
  AppCallRoute: AppCallRoute,
  AppDixonRoute: AppDixonRoute,
  AppFlyersRoute: AppFlyersRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppInboxRoute: AppInboxRoute,
  AppMyWeekRoute: AppMyWeekRoute,
  AppNotesRoute: AppNotesRoute,
  AppOffersRoute: AppOffersRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPlaybookRoute: AppPlaybookRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicDixonSplatRoute: ApiPublicDixonSplatRoute,
  ApiPublicGoogleCallbackRoute: ApiPublicGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
