/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppPlaybookRouteImport } from './routes/_app/playbook'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppMyWeekRouteImport } from './routes/_app/my-week'
import { Route as AppFollowUpsRouteImport } from './routes/_app/follow-ups'
import { Route as AppCallRouteImport } from './routes/_app/call'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppPlaybookRoute = AppPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppMyWeekRoute = AppMyWeekRouteImport.update({
  id: '/my-week',
  path: '/my-week',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowUpsRoute = AppFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AppRoute,
} as any)
const AppCallRoute = AppCallRouteImport.update({
  id: '/call',
  path: '/call',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/call': typeof AppCallRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/my-week': typeof AppMyWeekRoute
  '/pipeline': typeof AppPipelineRoute
  '/playbook': typeof AppPlaybookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/call': typeof AppCallRoute
  '/follow-ups': typeof AppFollowUpsRoute
  '/my-week': typeof AppMyWeekRoute
  '/pipeline': typeof AppPipelineRoute
  '/playbook': typeof AppPlaybookRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/call': typeof AppCallRoute
  '/_app/follow-ups': typeof AppFollowUpsRoute
  '/_app/my-week': typeof AppMyWeekRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/playbook': typeof AppPlaybookRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/call'
    | '/follow-ups'
    | '/my-week'
    | '/pipeline'
    | '/playbook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/call'
    | '/follow-ups'
    | '/my-week'
    | '/pipeline'
    | '/playbook'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/call'
    | '/_app/follow-ups'
    | '/_app/my-week'
    | '/_app/pipeline'
    | '/_app/playbook'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/playbook': {
      id: '/_app/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AppPlaybookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-week': {
      id: '/_app/my-week'
      path: '/my-week'
      fullPath: '/my-week'
      preLoaderRoute: typeof AppMyWeekRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/follow-ups': {
      id: '/_app/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AppFollowUpsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call': {
      id: '/_app/call'
      path: '/call'
      fullPath: '/call'
      preLoaderRoute: typeof AppCallRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCallRoute: typeof AppCallRoute
  AppFollowUpsRoute: typeof AppFollowUpsRoute
  AppMyWeekRoute: typeof AppMyWeekRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppPlaybookRoute: typeof AppPlaybookRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallRoute: AppCallRoute,
  AppFollowUpsRoute: AppFollowUpsRoute,
  AppMyWeekRoute: AppMyWeekRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppPlaybookRoute: AppPlaybookRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
